### ISSUE TITLE
PHP Fatal Error

### ISSUE THREAD

**Issue by Lindstromer** [eriktorsner/wp-checksum#11]
Seems like there's an issue, that I'm guessing is related to PHP 7.3. It gives a fatal error:

```diff
Checksum diff for plugin autoptimize readme.txt

Fatal error: Uncaught Error: Cannot use object of type WP_Error as array in /www/website.com/vendor/eriktorsner/wp-checksum/src/ApiClient.php:277
Stack trace:
#0 /www/website.com/vendor/eriktorsner/wp-checksum/src/ApiClient.php(226): WPChecksum\ApiClient->getApiKey()
#1 /www/website.com/vendor/eriktorsner/wp-checksum/src/FileDiff.php(135): WPChecksum\ApiClient->getFile('plugin', 'autoptimize', '2.5.1', 'readme.txt')
#2 /www/website.com/vendor/eriktorsner/wp-checksum/src/FileDiff.php(44): WPChecksum\FileDiff->getPluginFiles('autoptimize', 'readme.txt')
#3 /www/website.com/vendor/eriktorsner/wp-checksum/src/Checksum.php(355): WPChecksum\FileDiff->getDiff('plugin', 'autoptimize', 'readme.txt', 'diff')
#4 [internal function]: WPChecksum\Checksum->diff(Array, Array)
#5 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(67): call_user_func(Array, Array, Array)
#6 [internal function]: WP_CLI\Dispatcher\CommandFactory in /www/website.com/vendor/eriktorsner/wp-checksum/src/ApiClient.php on line 277
Error: Webbplatsen har tekniska problem.
Process completed with status 255
```

Gave it a quick check and I can get it running with the same repos (tried on multiple sites) when doing it with PHP 7.1 locally.

**Comment by Lindstromer** [comment]
Hörde att det ger samma fel i PHP 7.1 för en annan person så det är nog knappast PHP-versionen isf.

**Comment by eriktorsner** [comment]
Thanks for the report Olaf. I will troubleshoot asap.

--

/Erik Torsner
Tel: 0733-118503

**Comment by edgarmarkosov** [comment]
Are there any news for this fatal error?
